### ISSUE TITLE
nav.css Bug Report

### ISSUE THREAD

**Issue by ZeckXenial** [ZeckXenial/CarShop#13]
Here are the potential issues with the given code:

1. The class name in this selector is incorrect. It should be `.navbar` instead of `.nav`.
```css
.nav {
    background-color: darkslategrey;
}
```
2. There is a typo in this selector. It should be `.container .mdb-navbar .mdb-btn` instead of `.container MDBNavbar MDBBtn`.
```css
.container MDBNavbar MDBBtn{
    width: 50px;
    background-color: lightcyan;
}
```
3. The `width: unset;` property in this selector is unnecessary, as `unset` is the default value for width.
```css
.container header {
    width: unset;
    text-align: center;
}
```
4. The `position: absolute;` property in this selector may cause the image to overlap other elements. It's also unclear what the `right: 15px; top: 50px;` properties are intended to do, as they may position the image differently depending on the size of the viewport.
```css
.container img {
    position: absolute; right: 15px; top: 50px;
    width: 50px;
    display: flex;
    margin-right: 10px; 
    justify-content: right;
}
```
5. The `justify-content: center;` property in this selector is unnecessary, as it's already the default value.
```css
.container{
    justify-content: center;
}
```
Overall, the code could benefit from being more specific about the layout and positioning of elements, as well as using more descriptive class names.
